### ISSUE TITLE
Activating in terminator 1.91

### ISSUE THREAD

**Issue by flyasky** [ilgarm/terminator_plugins#6]
Activating this plugin in terminator 1.91 removes from menu all entries for other plugins

**Comment by Asynchronous003** [comment]
same here

plugin was throwing a gobject error on start so I changed therse lines-

import gi
from gi.repository import GObject as gobject
from gi.repository import Gtk as gtk

now I get no errors at start, but when I try to use plugin get these errors-

Traceback (most recent call last):
  File "/root/.config/terminator/plugins/clone_session.py", line 69, in clone_session
    sibling.spawn_child_with_command(cmd)
  File "/root/.config/terminator/plugins/clone_session.py", line 138, in spawn_child_with_command
    update_records = self.config['update_records']
  File "/usr/share/terminator/terminatorlib/config.py", line 283, in __getitem__
    return(self.base.get_item(key, self.profile, default=default))
  File "/usr/share/terminator/terminatorlib/config.py", line 741, in get_item
    raise KeyError('ConfigBase::get_item: unknown key %s' % key)
KeyError: 'ConfigBase::get_item: unknown key update_records'

I know this plugin is old, but would be great if it worked, yet I have no idea how to fix it,
any help would be much appreciated, Thanks :)

terminator 1.91
Linux kali 4.9.0-kali4-686 #1 SMP Debian 4.9.30-2kali1 (2017-06-22) i686 GNU/Linux

**Comment by liangjiezhu** [comment]
the same error
